services:
  neo4j:
    image: neo4j:5.9
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password # Default username/password
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt Protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  go-app:
    build:
      context: .
      dockerfile: Dockerfile # The location of the Dockerfile
    container_name: go-task-app
    ports:
      - "8080:8080" # Exposing port for the Go app
      - "3000:3000" # gin port
    environment:
      - NEO4J_URL=neo4j://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j
    volumes:
      - .:/app # Mount the current directory to /app inside the container
      - /app/vendor # Optionally mount vendor directory if using Go modules

volumes:
  neo4j_data:
  neo4j_logs:
