version: '3.9'

services:
  neo4j:
    image: neo4j:5.9
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password # Default username/password
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt Protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs:
